### ISSUE TITLE
Software Development and tools (1 feature implemented)

### ISSUE THREAD

**Issue by ianmclaren** [ianmclaren/SENG371Group#21]
Plan the tools you will use to develop the software. Get Familiar with the Technology/IDE/frameworks you are using. Start to develop the system.

Note: While it doesn't say so in the Assignment description, in the rubric it states we need 1 feature fully functioning

**Comment by szeckirjr** [comment]
I assigned myself to this just cause I started more work under `wardo/initial-setup` but everyone should assign themselves to this when they do development
