### ISSUE TITLE
Request for Changes Doc

### ISSUE THREAD

**Issue by szeckirjr** [ianmclaren/SENG371Group#27]
After meeting with Developers. Write up a request for changes in requirement document as clients for your developer Team. Work as a team and think about changes in detail for the developers. Make sure to send the Document to your developer team before the second lab. This should be a separate document from the requirement Document. Make sure the changes are with respect to functionalities and are feasible and not like changing of platform etc.

**Comment by Shake1999** [comment]
Added the four changes to the doc
